// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.0
// source: proto/chat/v1/chat.proto

package chatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 基本的聊天訊息結構
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                // 訊息唯一識別碼
	Sender        string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`        // 發送者ID
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`      // 訊息內容
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 發送時間戳（Unix timestamp）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 發送訊息請求
type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"` // 接收者ID
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`   // 訊息內容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 發送訊息回應
type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`  // 已發送的訊息
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"` // 發送是否成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SendMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 接收訊息請求
type ReceiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 接收訊息的用戶ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveRequest) Reset() {
	*x = ReceiveRequest{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveRequest) ProtoMessage() {}

func (x *ReceiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveRequest.ProtoReflect.Descriptor instead.
func (*ReceiveRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ReceiveRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_proto_chat_v1_chat_proto protoreflect.FileDescriptor

const file_proto_chat_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x18proto/chat/v1/chat.proto\x12\achat.v1\"i\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"J\n" +
	"\x12SendMessageRequest\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"[\n" +
	"\x13SendMessageResponse\x12*\n" +
	"\amessage\x18\x01 \x01(\v2\x10.chat.v1.MessageR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\")\n" +
	"\x0eReceiveRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId2\x9b\x01\n" +
	"\vChatService\x12J\n" +
	"\vSendMessage\x12\x1b.chat.v1.SendMessageRequest\x1a\x1c.chat.v1.SendMessageResponse\"\x00\x12@\n" +
	"\x0fReceiveMessages\x12\x17.chat.v1.ReceiveRequest\x1a\x10.chat.v1.Message\"\x000\x01B7Z5github.com/FZskycoding/GoChatRPC/proto/chat/v1;chatpbb\x06proto3"

var (
	file_proto_chat_v1_chat_proto_rawDescOnce sync.Once
	file_proto_chat_v1_chat_proto_rawDescData []byte
)

func file_proto_chat_v1_chat_proto_rawDescGZIP() []byte {
	file_proto_chat_v1_chat_proto_rawDescOnce.Do(func() {
		file_proto_chat_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chat_v1_chat_proto_rawDesc), len(file_proto_chat_v1_chat_proto_rawDesc)))
	})
	return file_proto_chat_v1_chat_proto_rawDescData
}

var file_proto_chat_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_chat_v1_chat_proto_goTypes = []any{
	(*Message)(nil),             // 0: chat.v1.Message
	(*SendMessageRequest)(nil),  // 1: chat.v1.SendMessageRequest
	(*SendMessageResponse)(nil), // 2: chat.v1.SendMessageResponse
	(*ReceiveRequest)(nil),      // 3: chat.v1.ReceiveRequest
}
var file_proto_chat_v1_chat_proto_depIdxs = []int32{
	0, // 0: chat.v1.SendMessageResponse.message:type_name -> chat.v1.Message
	1, // 1: chat.v1.ChatService.SendMessage:input_type -> chat.v1.SendMessageRequest
	3, // 2: chat.v1.ChatService.ReceiveMessages:input_type -> chat.v1.ReceiveRequest
	2, // 3: chat.v1.ChatService.SendMessage:output_type -> chat.v1.SendMessageResponse
	0, // 4: chat.v1.ChatService.ReceiveMessages:output_type -> chat.v1.Message
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_chat_v1_chat_proto_init() }
func file_proto_chat_v1_chat_proto_init() {
	if File_proto_chat_v1_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chat_v1_chat_proto_rawDesc), len(file_proto_chat_v1_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chat_v1_chat_proto_goTypes,
		DependencyIndexes: file_proto_chat_v1_chat_proto_depIdxs,
		MessageInfos:      file_proto_chat_v1_chat_proto_msgTypes,
	}.Build()
	File_proto_chat_v1_chat_proto = out.File
	file_proto_chat_v1_chat_proto_goTypes = nil
	file_proto_chat_v1_chat_proto_depIdxs = nil
}
